// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_JmDwT0h_Dfj02qC4HjZGuRVN9-uTkXQ',
    appId: '1:738007946237:web:06fc51847ebc4ed889ff94',
    messagingSenderId: '738007946237',
    projectId: 'todo-app-6c94f',
    authDomain: 'todo-app-6c94f.firebaseapp.com',
    databaseURL: 'https://todo-app-6c94f-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-6c94f.appspot.com',
    measurementId: 'G-YK1N5NHLBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7v5eHH2Yi7NXFL-Url7GqCwBv9_7CbTU',
    appId: '1:738007946237:android:556f6be48a1dda3589ff94',
    messagingSenderId: '738007946237',
    projectId: 'todo-app-6c94f',
    databaseURL: 'https://todo-app-6c94f-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-6c94f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiFhI-6fJqwa_-ZItfWF_Eq74LqIAUTQU',
    appId: '1:738007946237:ios:0fe4ed592edc513e89ff94',
    messagingSenderId: '738007946237',
    projectId: 'todo-app-6c94f',
    databaseURL: 'https://todo-app-6c94f-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-6c94f.appspot.com',
    iosClientId: '738007946237-qss6csjc3sn3iveao88dtrt44qssultp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiFhI-6fJqwa_-ZItfWF_Eq74LqIAUTQU',
    appId: '1:738007946237:ios:0fe4ed592edc513e89ff94',
    messagingSenderId: '738007946237',
    projectId: 'todo-app-6c94f',
    databaseURL: 'https://todo-app-6c94f-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-6c94f.appspot.com',
    iosClientId: '738007946237-qss6csjc3sn3iveao88dtrt44qssultp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleProject',
  );
}
